resolver: lts-11.5
packages:
  - '.'
extra-deps:
  - heist-1.0.1.2
  - map-syntax-0.2.0.2
  - snap-1.1.0.0
  - xmlhtml-0.2.5.2
  - blaze-html-0.9.0.1
  - blaze-markup-0.8.2.1
flags:
  snaplet-persistent:
    lib-Werror: true
extra-package-dbs: []
