resolver: lts-9.21
packages:
  - '.'
extra-deps:
  - heist-1.0.1.1
  - map-syntax-0.2.0.2
  - snap-1.0.0.2
  - xmlhtml-0.2.5.2
  # for lts 8/9
  - blaze-html-0.9.0.1
  - blaze-markup-0.8.1.0
flags:
  snaplet-persistent:
    lib-Werror: true
extra-package-dbs: []
