resolver: lts-14.27
packages:
  - '.'
extra-deps:
  - heist-1.1.0.1
  - map-syntax-0.3
  - snap-1.1.3.0
  - xmlhtml-0.2.5.2
  - blaze-html-0.9.1.2
  - blaze-markup-0.8.2.5
  - pwstore-fast-2.4.4
  - lift-type-0.1.0.1
  - persistent-2.13.3.5
  - persistent-postgresql-2.13.5.0
flags:
  snaplet-persistent:
    lib-Werror: true
extra-package-dbs: []
